# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sistemaweb.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combinar',
            fields=[
                ('combinar_id', models.AutoField(primary_key=True, serialize=False)),
                ('combinar_alternativas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comparar',
            fields=[
                ('comparar_id', models.AutoField(primary_key=True, serialize=False)),
                ('comparar_archivo_idf1', models.FileField(upload_to='comparacion_idf/', validators=[sistemaweb.validators.validacion_extension_idf])),
                ('comparar_archivo_idf2', models.FileField(upload_to='comparacion_idf/', validators=[sistemaweb.validators.validacion_extension_idf])),
            ],
        ),
        migrations.CreateModel(
            name='Construccion',
            fields=[
                ('construccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('construccion_outside', models.FloatField()),
                ('construccion_layer2', models.FloatField()),
                ('construccion_layer3', models.FloatField()),
                ('construccion_layer4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=150)),
                ('material_roughness', models.FloatField()),
                ('material_thickness', models.FloatField()),
                ('material_conductivity', models.FloatField()),
                ('material_density', models.FloatField()),
                ('material_specific_heat', models.FloatField()),
                ('material_thermal_absorptance', models.FloatField()),
                ('material_solar_absorptance', models.FloatField()),
                ('construccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaweb.Construccion')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('materials_id', models.AutoField(primary_key=True, serialize=False)),
                ('materials_name', models.CharField(max_length=150)),
                ('materials_dsb_name', models.CharField(max_length=140)),
                ('materials_type', models.CharField(choices=[('MA', 'MATERIAL'), ('NO', 'MATERIAL_NOMASS'), ('GL', 'WINDOWS_MATERIAL_GLAZING'), ('GA', 'WINDOWS_MATERIAL_GAS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Modificar',
            fields=[
                ('modificar_id', models.AutoField(primary_key=True, serialize=False)),
                ('modificar_archivo_idf', models.FileField(upload_to='modificacion_idf/', validators=[sistemaweb.validators.validacion_extension_idf])),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSimulacion',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('reporte_totalenergy_totalsite', models.FloatField()),
                ('reporte_totalenergy_totalsource', models.FloatField()),
                ('reporte_distric_heating_heating', models.FloatField()),
                ('reporte_distric_time_etpoint', models.FloatField()),
                ('reporte_heating_intensity_hvac', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Simular',
            fields=[
                ('simular_id', models.AutoField(primary_key=True, serialize=False)),
                ('simular_clima', models.FileField(upload_to='epw/', validators=[sistemaweb.validators.validacion_extension_epw])),
                ('simular_archivo_idf', models.FileField(upload_to='idf/', validators=[sistemaweb.validators.validacion_extension_idf])),
            ],
        ),
    ]
