# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construccion',
            fields=[
                ('construccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('construccion_outside', models.FloatField()),
                ('construccion_layer2', models.FloatField()),
                ('construccion_layer3', models.FloatField()),
                ('construccion_layer4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=150)),
                ('material_roughness', models.FloatField()),
                ('material_thickness', models.FloatField()),
                ('material_conductivity', models.FloatField()),
                ('material_density', models.FloatField()),
                ('material_specific_heat', models.FloatField()),
                ('material_thermal_absorptance', models.FloatField()),
                ('material_solar_absorptance', models.FloatField()),
                ('construccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaweb.Construccion')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSimulacion',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('reporte_totalenergy_totalsite', models.FloatField()),
                ('reporte_totalenergy_totalsource', models.FloatField()),
                ('reporte_distric_heating_heating', models.FloatField()),
                ('reporte_distric_time_etpoint', models.FloatField()),
                ('reporte_heating_intensity_hvac', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Simular',
            fields=[
                ('simular_id', models.AutoField(primary_key=True, serialize=False)),
                ('simular_clima', models.FileField(upload_to='epw/')),
                ('simular_archivo_idf', models.FileField(upload_to='idf/')),
            ],
        ),
    ]
