# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import sistemaweb.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simular',
            name='simular_archivo_idf',
            field=models.FileField(upload_to='idf/', validators=[sistemaweb.validators.validacion_extension_idf]),
        ),
        migrations.AlterField(
            model_name='simular',
            name='simular_clima',
            field=models.FileField(upload_to='epw/', validators=[sistemaweb.validators.validacion_extension_epw]),
        ),
    ]
